development:
  adapter: postgresql
  encoding: unicode
  database: league_champion_db
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: sinatra-project-production